### ISSUE TITLE
All the games in my collection appear as "not in my collection".

### ISSUE THREAD

**Issue by amselem** [przepinski/bgguwp#2]
When querying a game card that is in my collection, it looks like the game is not in my collection because the "+ Add" button is shown. 
If I press this button a 2nd copy of the game gets added in my collection (as shown in BGG website)

**Comment by rzepinskip** [comment]
I wasn't able to reproduce this unexpected behaviour. Could you provide any screenshots?

As soon as collection item connected with board game is loaded the edit and save commands should reflect this change with being enabled and disabled. So, in your case it seems that collection item is not found in local DB due to some network problems(?).

Will look into that when crash reports are delivered.

**Comment by rzepinskip** [comment]
Should be fixed with 7710fdef0dbe503be193ec71fd7c36815cf917d9. Please, confirm when 1.2.1.0 update will be released.

**Comment by amselem** [comment]
Hi
It's working now! I'm glad you found the cause.
The bad news is I have found another new bugs, I think they're caused by fixing this issue. 
I'll open new issues for these bugs.
